version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev-251205"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev-liji"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev_backup_20251121"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev-251205"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev-liji"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev_backup_20251121"
  - package-ecosystem: "npm"
    directory: "/free-todo-frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/free-todo-frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/free-todo-frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev-251205"
  - package-ecosystem: "npm"
    directory: "/free-todo-frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev-liji"
  - package-ecosystem: "npm"
    directory: "/free-todo-frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev_backup_20251121"
